blank_issues_enabled: false
contact_links:
  - name: âš›ï¸ React Native Issue
    url: https://github.com/facebook/react-native/issues
    about: Please report bugs or issues in the React Native repository.
  - name: â¤´ï¸ Upgrade Issue
    url: https://github.com/react-native-community/upgrade-support
    about: Need help upgrading to a newer React Native version? Visit the Upgrade Support repository.
  - name: ğŸ¤” Questions and Help
    url: https://reactnative.dev/help
    about: Looking for help with your app? Please refer to the React Native community's support resources.
  - name: ğŸš€ React Native Discussions and Feature Proposals
    url: https://github.com/react-native-community/discussions-and-proposals
    about: Discuss the future of React Native in the React Native community's discussions and proposals repository.
