name: Pre-merge

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Check lock for duplications
        run: yarn dedupe --check

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check dependencies alignment
        run: yarn check-dependencies

      - name: "[TEMP] Debug bins"
        run: |
          yarn workspaces foreach \
            --all \
            --parallel \
            --topological \
            exec sh -c '
            test -f package.json || exit 0
            jq -r "
            .bin?
            | to_entries[]
            | \"\(.key) â†’ \(.value)\"
            " package.json \
              | sed "s|^|$(pwd)/|"
            '

      - name: Run Lint
        run: yarn ci:lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
        working-directory: website
        env:
          NODE_OPTIONS: --max_old_space_size=8192
